name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'aws-gpu-spot-monitor/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./aws-gpu-spot-monitor
      run: npm ci
    
    - name: Run backend tests
      working-directory: ./aws-gpu-spot-monitor
      run: npm test -- --coverage
    
    - name: Upload backend test coverage
      uses: actions/upload-artifact@v3
      with:
        name: backend-coverage
        path: aws-gpu-spot-monitor/coverage
  
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'aws-gpu-spot-monitor/frontend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./aws-gpu-spot-monitor/frontend
      run: npm ci
    
    - name: Run frontend tests
      working-directory: ./aws-gpu-spot-monitor/frontend
      run: npm test -- --coverage
    
    - name: Upload frontend test coverage
      uses: actions/upload-artifact@v3
      with:
        name: frontend-coverage
        path: aws-gpu-spot-monitor/frontend/coverage
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'aws-gpu-spot-monitor/package-lock.json'
    
    - name: Install backend dependencies
      working-directory: ./aws-gpu-spot-monitor
      run: npm ci
    
    - name: Run backend linting
      working-directory: ./aws-gpu-spot-monitor
      run: npm run lint
    
    - name: Install frontend dependencies
      working-directory: ./aws-gpu-spot-monitor/frontend
      run: npm ci
    
    - name: Run frontend linting
      working-directory: ./aws-gpu-spot-monitor/frontend
      run: npm run lint