name: Frontend Build

on:
  push:
    branches: [ main ]
    paths:
      - 'aws-gpu-spot-monitor/frontend/**'
      - '.github/workflows/frontend-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'aws-gpu-spot-monitor/frontend/**'
      - '.github/workflows/frontend-build.yml'

env:
  NODE_VERSION: '18'

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'aws-gpu-spot-monitor/frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./aws-gpu-spot-monitor/frontend

      - name: Build
        run: npm run build
        working-directory: ./aws-gpu-spot-monitor/frontend

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: aws-gpu-spot-monitor/frontend/build
          retention-days: 7